import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Suspense } from "react";
import Loading from "./loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Suspense fallback={<Loading />}>
      <html lang="es" suppressHydrationWarning>
        <body
          className={
            `${geistSans.variable} ${geistMono.variable} bg-[#FDFCF9]`
          }
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="ligth"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </Suspense>
  );
}
